-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 18:47:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
DROP DATABASE IF EXISTS consultas;
CREATE DATABASE consultas;
use consultas;
-- -----------------------------------------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultas`.`Funcionario` (
  `idFuncionario` INT NOT NULL auto_increment,
  `nomesobrenome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultas`.`Medico` (
  `idMedico` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  `CRM` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultas`.`paciente` (
  `idPaciente` INT auto_increment,
  `nomesobrenome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `valorconsulta` INT NULL,
  `cpf` VARCHAR(45) NULL,
  `Funcionario_idFuncionario` INT,
  PRIMARY KEY (`idPaciente`, `Funcionario_idFuncionario`),
  INDEX `fk_Paciente_Funcionario_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Paciente_Funcionario`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `consultas`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultas`.`Paciente_has_Medico` (
  `Paciente_idPaciente` INT NOT NULL,
  `Paciente_Funcionario_idFuncionario` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`Paciente_idPaciente`, `Paciente_Funcionario_idFuncionario`, `Medico_idMedico`),
  INDEX `fk_Paciente_has_Medico_Medico1_idx` (`Medico_idMedico` ASC),
  INDEX `fk_Paciente_has_Medico_Paciente1_idx` (`Paciente_idPaciente` ASC, `Paciente_Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Paciente_has_Medico_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente` , `Paciente_Funcionario_idFuncionario`)
    REFERENCES `consultas`.`Paciente` (`idPaciente` , `Funcionario_idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Medico_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `consultas`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
